url : https://project1.qualibytes.com/backend/admin/index.php
username : admin@mail.com
password : Password@123


       // created 3 variable and stored that value//
       // config.properties is used to store hard coded value//