package Testng;

import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.chrome.ChromeOptions;
import org.testng.annotations.Test;



import io.github.bonigarcia.wdm.WebDriverManager;
import junit.framework.Assert;

public class HMS {

	@Test
	public void loginHMS()                              // execute this via clicking on run 
	{
		    WebDriverManager.chromedriver().setup();
		    
		    ChromeOptions options = new ChromeOptions();
			
			options.addArguments("--remote-allow-origins=*");
			
			WebDriver driver = new ChromeDriver(options);   // launch the browser0
			
			driver.manage().window().maximize();
			
			driver.get("https://project1.qualibytes.com/backend/admin/index.php"); 
			
			Assert.assertTrue(false);
	}
}



                 // 2nd method to run this program is to right click on hms and click on testng and click on convert to testng and change suite name, test name
                  // simply click on testing.xml and run this program
                  // click on test output under hms and click on login then see generated report by default its generated
                  // it generated 2type of report ie. general report ie emailable report and index.html report which generated by default

                  // apart from 2reports to generate new report we used extendsclass 